# Generated by Django 2.1.1 on 2018-09-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180926_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布'), (2, '撤销'), (3, '删除')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Label', verbose_name='栏目'),
        ),
    ]
