# Generated by Django 2.1.1 on 2018-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180930_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article/%Y/%m/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=100, verbose_name='分类'),
        ),
    ]
