# Generated by Django 2.1.1 on 2018-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181008_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='statu',
            field=models.IntegerField(choices=[(0, '未发布'), (1, '已发布'), (2, '撤销'), (3, '删除')], default=1, verbose_name='状态'),
        ),
    ]
