# Generated by Django 2.1.1 on 2018-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20181008_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='article/%Y/%m/', verbose_name='图片'),
        ),
    ]
