# Generated by Django 2.1.1 on 2018-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181010_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='article/%Y/%m/', verbose_name='图片'),
        ),
    ]
