# Generated by Django 2.1.1 on 2018-10-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, '已发布'), (1, '已删除')], default=0, verbose_name='状态'),
        ),
    ]
